src/backend/pg.rs, src/lib.rs, src/tests/pg/add_column.rs
Fixes #13
Allow to define a custom column type not explicitly declared on the migration system with the `add_column()` command.
This limits the static checker security, but also allows much more flexibility using extensions and custom backend types.
=> Add a custom column type

guides/diesel-setup.md
The `diesel` dependency never had a `barrel-migrations`-feature, only `diesel_cli` have one.
The command line for barrel migrations changed (`--format` instead of `--type`).
I also bumped the diesel version.
=> update diesel integration documentation

.travis.yml
As barrel currently only builds on nightly travis tests should fail on nightly.
=> travis: fail on nightly build error

src/migration.rs, src/tests/pg/create_table.rs, src/tests/sqlite3/create_table.rs, src/tests/sqlite3/mod.rs
End each migration with an `;` to allow multiple migrations.
=> seperate migrations

src/backend/pg.rs, src/tests/pg/add_column.rs
The SQL standard doesn't define a `BINARY` type and postgres uses `BYTEA` for binary data.
https://www.postgresql.org/docs/9.0/static/datatype-binary.html
=> fixes BINARY column type in psql

src/backend/pg.rs, src/tests/pg/create_table.rs, src/tests/pg/simple.rs
When I use the `Pg::drop_table_if_exists` it generates the following statement:  `DROP TABLE "Scoring" IF EXISTS;`  which causes the following error: `syntax error at or near \"IF\"`.
I double-checked the [Postgres docs table docs](https://www.postgresql.org/docs/11/sql-droptable.html)  
This PR changes the output to be `DROP  TABLE IF EXISTS "Scoring";`
=> Pg: Postgres `drop_table_if_exists` generates the wrong statement

src/backend/mysql.rs, src/migration.rs, src/tests/mysql/simple.rs
Looks like the Migration generator was lacking support for changing a table. I've added the basic code to handle that.
=> Add support for altering a table

README.md, src/lib.rs
This PR is a bunch of small changes to make the docs better.
For one, it finally updates the `README.md` to the new API
that's coming in 0.5.0 (removing yet another blocker for
that release!)
Additionally I finally fixed the doc tests in the crate docs.
They were always set to `ignore` which irked me.
Now they just don't show some behind-the-scenes code that's
required to make it all work.
Incidentally, while writing the doc tests for `Migration::execute`
I noticed that the usability there really could be improved.
=> Improving documentation for 0.5.0 release

src/migration.rs, src/table.rs, src/tests/common/mod.rs, src/tests/mysql/create_table.rs, src/tests/pg/create_table.rs, src/tests/sqlite3/create_table.rs
I updated the match arm to match the name same name of the function that was added to the changes vector.  Here's the code I was using to test.  This should resolve #45 
```
use barrel::backend::Pg;
use barrel::types;
use barrel::*;
#[derive(Clone, Debug)]
pub struct ColumnDef{
pub name: String,
pub data_type: String,
}
fn main() {
let mut m = Migration::new();
m.create_table_if_not_exists("my_table", move |t| {
let columns: Vec<ColumnDef> = vec![ ColumnDef { name: String::from("col1"), data_type: String::from("varchar(32)") } ];
for col in columns {
let cname: &str = &col.name;
t.add_column(cname, types::varchar(255));
}
}).without_id();
}
```
I will be adding a test for this.
=> changed match arm to match create_table_if_not_exists

src/connectors.rs, src/lib.rs, src/migration.rs
This also includes documentation updates as well
as some minor quality-of-life changes such as the
order of the Generic parameters
=> Renaming `DatabaseExecutor` to `SqlRunner` to sound less Java

src/lib.rs
Not entirely sure why this was added in the first place.
But I kinda feel this shouldn't be included anymore.
Potentially it will make debugging integrations harder but
who are we to tell people how to use the barrel type system?
=> Removing compilation gate requiring an Sql backend to be selected

src/backend/mod.rs, src/backend/mysql.rs, src/backend/pg.rs, src/backend/sqlite3.rs, src/migration.rs, src/table.rs, src/tests/mysql/simple.rs, src/tests/pg/simple.rs, src/tests/sqlite3/simple.rs
This PR adds the ability to prefix tables with a database schema.
The API has supported this feature for a _long_ time but for some
reason the feature was silently removed in a refactoring (woops).
Test coverage is still a bit lacking. This is adding a single test
for each backend to make sure it roughly works. And most importantly
tests that non-schema prefixed actions don't break existing tests :)
=> Implementing table schemas

src/lib.rs, src/table.rs
This makes it possible to work around missing `barrel` features
without hitting a wall.
=> Adding `CustomLine` change to allow Sql injection into migrations

README.md, examples/user_index.rs, src/backend/mod.rs, src/backend/mysql.rs, src/backend/pg.rs, src/backend/sqlite3.rs, src/lib.rs, src/migration.rs, src/table.rs, src/tests/common/utils.rs, src/types/builders.rs, src/types/impls.rs
This PR adds support for database indices. They are handled as part of the table constructor, although exist outside of the regular table changeset.
This is done to have an index change be scoped to a table (i.e. as far as I can tell, no database really supports multi-table indecies this way anyway), without having to match on changes when building a changeset.
An index addition is always handled on the same scope as creating a table.
The open tracking issue for this PR is #54
=> Initial `index` support (#63) fixes #54

examples/sqlite_strings.rs, src/backend/mysql.rs, src/backend/pg.rs, src/backend/sqlite3.rs, src/tests/common/mod.rs, src/tests/sqlite3/create_table.rs, src/types/builders.rs, src/types/defaults.rs, src/types/impls.rs, src/types/mod.rs
This PR changes the way that the `types::primary()` builder works and
adds a `primary(bool)` function to the Type pattern. The `PRIMARY`
base type still exists, but is handled seperately, for Pg reasons
(should be removed next version).  All other types that use the
`primary(...)` function will be able to become `PRIMARY KEY` in the
generated SQL.
Additionally this PR fixes the way that `WrappedDefault` values are
encoded. i.e. it is now possible to properly specify a default value
that is then mapped into the apropriate type.
=> Implementing "any primary key" feature and default redering

src/integrations/diesel.rs
The tmp package wouldn't build because the feature specified by the
backend wasn't properly wrapped in quotes. Cargo would complain about
parsing the `Cargo.toml` file.
The error that would be returned is:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/5eeb567a27eba18420a620ca7d0c007e29d8bc0c/src/libcore/slice/mod.rs:2695:10
```
This happened because the tmp package was never built since it failed in parsing the `Cargo.toml` file.
=> Fix issue with running `diesel migrations list`

src/backend/mysql.rs, src/backend/pg.rs, src/backend/sqlite3.rs
During my work for Prisma, I saw that index creation through Barrel didn't work for MySQL and SQLite. This PR rectifies that.
=> Fix index creation for MySQL and SQLite

src/tests/mysql/add_column.rs, src/tests/mysql/mod.rs
This is about the comment I've made in issue https://github.com/rust-db/barrel/issues/8#issuecomment-522310606.
In **summary**, the tests in tests/mysql/add_column.rs aren't run because they're not in tests/mysql/mod.rs. This change includes the add_column tests.
The changes are grouped into 2 commits:
1. Fixing compile errors
2. Fixing test failures
Detailed description of the changes are included in the commit messages.
Please let me know if you have any suggestions to improve this PR.
=> Include MySQL add_column tests

Cargo.toml, src/lib.rs
Fix compilation warnings via `cargo fix`, also rename `website` to `homepage` in Cargo.toml.
=> Fix warnings

Cargo.toml, src/integrations/diesel.rs
`tempdir` has been deprecated after being merged into `tempfile`
=> Replace tempdir with tempfile

README.md
let's is "let us", lets is present-tense let
=> Small grammar fix for let's → lets

src/backend/mysql.rs, src/tests/mysql/create_table.rs, src/tests/mysql/simple.rs
In MySql the table name is placed after `IF`, not before:
```sql
CREATE TABLE IF NOT EXISTS `snippet` (`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY);
DROP TABLE IF EXISTS `snippet`;
```
=> Use correct syntax for `CREATE TABLE IF NOT EXISTS` and `DROP TABLE IF EXISTS` in MySql backend
